### ISSUE TITLE
Run on Orange Pi

### ISSUE THREAD

**Issue by javipsantos** [smittytone/HT16K33Segment-Python#1]
Hello. I am trying to implement your code in a Orange Pi, but i have a problem with `busio `module. I install adafruit-blinka but still having the problem. I also installed WiringOP and the system recognize the HT16K33 in 0x70:

```
orangepi@orangepiplus2e:~/HT16K33Segment-Python$ sudo i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --
```

This is my code:

```
#!/usr/bin/env python3

from htk1633segment_micropython import HT16K33Segment

import busio
from board import *
i2c = busio.I2C(board.SCL, board.SDA)
led = HT16K33Segment(i2c)

#Turn down the display brightness
led.set_brightness(1)

#Set the display to --:--
led.set_char("-", 0)
led.set_char("-", 1)
led.set_char("-", 2)
led.set_char("-", 3)
led.set_colon(true)
led.update()
```

And this is the response:
```
$ sudo python3 dis.py
Traceback (most recent call last):
  File "dis.py", line 5, in <module>
    import busio
ModuleNotFoundError: No module named 'busio'
```

Do you know if is possible to use it in a Orange Pi?. Thank you in advance.

**Comment by javipsantos** [comment]
Hi again. I realized that I could install CircuitPython without blinka, but when I go to install it it gives me the error that I don't have setuptools but if they are installed:

orangepi@orangepiplus2e:~/circuitpython$ sudo apt-get install python3-setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-setuptools is already the newest version (40.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
orangepi@orangepiplus2e:~/circuitpython$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Thanks

**Comment by smittytone** [comment]
I haven't tried this, so no promises, but you probably want to use the module smbus, which is the standard Python I2C library, something like:

```
from htk1633segment_micropython import HT16K33Segment
import smbus
i2c = smbus.SMBus(1)
led = HT16K33Segment(i2c)
```

You'll also need to edit the HT16K33Segment library to change the *update()* and *write_cmd()* functions to use smbus functions to write data out to the I2C bus.

**Comment by javipsantos** [comment]
I'll try and tell.

Thank you very much.

**Comment by javipsantos** [comment]
Hi.
The module is not working anymore. Now i can't found it in i2c. I don't know why it stop working. I changed to Armbian based on Ubuntu (prev. working with Armbiam Debian) but the I2C bus does not detect the htk1633, maybe it is broken... 
When i have time i will test the htk1633 in arduino. Thank you four your help.

**Comment by smittytone** [comment]
I have not used the Orange Pi, or Armbian. But I have confirmed the code I suggested above works on a Raspberry Pi, so I'm going to update the library to add the code.

You should check that I2C is enabled under the new OS.
